catalog/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.get_index_page, name='index_page'),
    url(r'^filter$', views.filter_clothes, name='filter_clothes'),
    url(r'^contact', views.get_contact_page, name='contact'),
    url(r'^about_us', views.get_about_us_page, name='about_us'),
    url(r'^order', views.handle_order, name='order'),
]

clothes/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from solid_i18n.urls import solid_i18n_patterns
from django.utils.translation import ugettext_lazy as _

admin.site.site_header = _('Clothes Catalog')
admin.site.site_title = _('Clothes Catalog')
admin.site.index_title = _('Clothes Catalog')

urlpatterns = [
    # url(r'^(?P<filename>(robots.txt)|(humans.txt))$', home_files, name='home-files'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += solid_i18n_patterns(
    url(r'^', include('catalog.urls', namespace="catalog")),
    url(r'^admin/', include(admin.site.urls)),
)

catalog/models.py
from django.db import models
from collections import namedtuple
from django.utils.translation import ugettext_lazy as _
from django.utils.translation import pgettext_lazy
from django.conf import settings
from django.core.validators import RegexValidator
from django.utils import timezone
from easy_thumbnails.fields import ThumbnailerImageField


class Category(models.Model):
    title = models.CharField(max_length=255, verbose_name=_("Title"))
    description = models.TextField(verbose_name=_("Description"))
    url_name = models.CharField(max_length=255, verbose_name=_("Url Name"))


    def __str__(self):
        return self.title


    class Meta:
        verbose_name = _("Category")
        verbose_name_plural = _("Categories")


class Clothing(models.Model):
    Choice = namedtuple("Choice", ["key", "caption", "url_name"])
    FilterParameter = namedtuple("FilterParameter",
        ["caption", "field_name", "url_name", "choices"])

    genders = FilterParameter(
        _("Gender/Age"),
        "gender",
        pgettext_lazy("url", "gender"),
        (
            Choice(1, _("Men"), pgettext_lazy("url", "men")),
            Choice(2, _("Women"), pgettext_lazy("url", "women")),
            Choice(3, _("Unisex"), pgettext_lazy("url", "unisex")),
            Choice(4, _("Boys"), pgettext_lazy("url", "boys")),
            Choice(5, _("Girls"), pgettext_lazy("url", "girls")),
            Choice(6, _("Kids unisex"), pgettext_lazy("url", "kids_uni")),
        )
    )

    seasons = FilterParameter(
        _("Season"),
        "season",
        pgettext_lazy("url", "season"),
        (
            Choice(1, _("Winter"), pgettext_lazy("url", "winter")),
            Choice(2, _("Spring"), pgettext_lazy("url", "spring")),
            Choice(3, _("Summer"), pgettext_lazy("url", "summer")),
            Choice(4, _("Autumn"), pgettext_lazy("url", "autumn")),
            Choice(5, _("Uni"), pgettext_lazy("url", "uni")),
            Choice(6, _("Autumn/Winter"), pgettext_lazy("url", "autumn-winter")),
            Choice(7, _("Spring/Summer"), pgettext_lazy("url", "spring-summer")),
        )
    )

    filter_parameters = (seasons, genders)


    def get_filter_param_choices(choices_container):
        return tuple((ch.key, ch.caption) for ch in choices_container.choices)


    @classmethod
    def filter(cls, params):
        filtering_params = {}

        for param_url_name, choice_url_name in params.items():
            param = cls.get_filter_param_by_url_name(param_url_name)
            choice_key = cls.get_choice_db_key(param, choice_url_name)
            filtering_params[param.field_name] = choice_key

        return cls.objects.filter(**filtering_params)


    @staticmethod
    def get_choice_db_key(filtering_param, choice_url_name):
        for choice in filtering_param.choices:
            if choice.url_name == choice_url_name:
                return choice.key
        return None


    @classmethod
    def get_filter_param_by_url_name(cls, url_name):
        for filt in cls.get_filter_params():
            if url_name == filt.url_name:
                return filt
        return None


    @classmethod
    def get_filter_params(cls):
        categories = Category.objects.all()
        choices = tuple(cls.Choice(x.pk, x.title, x.url_name) for x in categories)
        categories_filter_param = cls.FilterParameter(
            _("Category"),
            "category",
            pgettext_lazy("url", "category"),
            choices
        )
        return cls.filter_parameters + (categories_filter_param,)


    def __str__(self):
        return self.title


    class Meta:
        verbose_name = _("Clothing")
        verbose_name_plural = _("Clothes")


    title = models.CharField(max_length=255, verbose_name=_("Title"))
    description = models.TextField(verbose_name=_("Description"), blank=True)
    photo = ThumbnailerImageField(upload_to='images', verbose_name=_("Photo"))
    gender = models.IntegerField(verbose_name=genders.caption,
        choices=get_filter_param_choices(genders))
    season = models.IntegerField(verbose_name=seasons.caption,
        choices=get_filter_param_choices(seasons))
    category = models.ForeignKey(Category, verbose_name=_("Category"))


class Option(models.Model):
    key = models.CharField(max_length=255, verbose_name=_("Key"), unique=True)
    value = models.TextField(max_length=255, verbose_name=_("Value"), null=True, blank=True)
    comment = models.CharField(max_length=255, verbose_name=_("Comment"), null=True, blank=True)


    def __str__(self):
        return self.key


    class Meta:
        verbose_name = _("Option")
        verbose_name_plural = _("Options")


    @classmethod
    def get_dynamic_options(cls):
        options = {}
        for key in settings.DYNAMIC_OPTIONS:
            try:
                options[key] = cls.objects.get(key=key).value
            except cls.DoesNotExist:
                options[key] = None
        return options


class Order(models.Model):
    phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$',
        message=_("Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed."))

    client_name = models.CharField(max_length=255, verbose_name=_("Client Name"))
    client_email = models.EmailField(max_length=255, verbose_name=_("Client Email"))
    client_company = models.CharField(max_length=255, null=True, blank=True,
        verbose_name=_("Client Company"))
    client_phone = models.CharField(max_length=255, null=True, blank=True,
        validators=[phone_regex], verbose_name=_("Client Phone"))
    order_text = models.TextField(verbose_name=_("Order Text"))
    time = models.DateTimeField(default=timezone.now, verbose_name=_("Order Time"))


    @classmethod
    def get_verbose_name(cls, field):
        return cls._meta.get_field(field).verbose_name.title()


    def __str__(self):
        self_str_representation = self.client_name
        if self.client_company:
            self_str_representation += ' - ' + self.client_company
        return self_str_representation


    class Meta:
        verbose_name = pgettext_lazy("Noun", "Order")
        verbose_name_plural = _("Orders")

catalog/forms.py
from django.utils.translation import ugettext_lazy as _
from django.forms import ModelForm
from .models import Order


class OrderForm(ModelForm):
    class Meta:
        model = Order
        fields = ['client_name', 'client_email',
            'client_company', 'client_phone', 'order_text']
        labels = {
            'client_name': _('Name'),
            'client_email': _('Email'),
            'client_company': _('Company'),
            'client_phone': _('Phone'),
            'order_text': _('Order Text'),
        }

catalog/views.py
from django.shortcuts import render, redirect
from django.core.paginator import Paginator
from django.core.exceptions import ValidationError
from django.core.urlresolvers import reverse
from django.core.mail import send_mail
from django.utils.translation import ugettext as _, activate, deactivate
from django.conf import settings
import datetime

from .models import Clothing, Option, Order
from .forms import OrderForm

def make_filters_list(current_filters=None):
    if current_filters is None:
        current_filters = {}

    filters = list(Clothing.get_filter_params())
    filters_list = [
        {
            "caption": f.caption,
            "url_name": f.url_name,
            "choices": make_choices(f, current_filters.get(f.url_name, None)),
        } for f in filters
    ]

    return filters_list


def make_choices(filt, currently_chosen):
    return [
        {
            "caption": x.caption,
            "url_name": x.url_name,
            "is_currently_chosen": x.url_name == currently_chosen
        } for x in filt.choices
    ]


def handle_request_params(request):
    # request.GET contain a list of values for each parameter
    # but we need only one value for each parameter, so we form new dict
    params = {key: request.GET[key] for key in request.GET}
    filters = {k: v for k, v in params.items() if k != "page"}
    page_num = int(params.get("page", 1))
    return filters, page_num


def get_index_page(request):
    clothes = Clothing.objects.all()
    paginator = Paginator(clothes, settings.ITEMS_PER_PAGE)

    return render_with_dynamic_options(request, "catalog/index.html", {
        "clothes": paginator.page(1),
        "filters_list": make_filters_list(),
    })


def filter_clothes(request):
    filters, page_num = handle_request_params(request)
    clothes = Clothing.filter(filters)
    paginator = Paginator(clothes, settings.ITEMS_PER_PAGE)

    return render_with_dynamic_options(request, "catalog/filter.html", {
        "clothes": paginator.page(page_num),
        "filters_list": make_filters_list(filters),
        "page_num": page_num,
        "pages_num": paginator.num_pages,
    })


def get_contact_page(request):
    return render_with_dynamic_options(request, "catalog/contact.html")


def get_about_us_page(request):
    return render_with_dynamic_options(request, "catalog/about_us.html")


def handle_order(request):
    if request.method == 'POST':
        return handle_order_post(request)
    else:
        return render_order_page(request)


def render_order_page(request):
    form = OrderForm()
    order_status = 'success' if 'order_success' in request.COOKIES else None

    response = render_with_dynamic_options(request, "catalog/order.html", {
        'order_status': order_status,
        'form': form,
    })
    response.delete_cookie('order_success')

    return response


def handle_order_post(request):
    form = OrderForm(request.POST)

    if form.is_valid():
        response = handle_new_order(request)
    else:
        response = render_with_dynamic_options(request, "catalog/order.html", {
            'order_status': 'fail',
            'form': form,
        })

    return response


def handle_new_order(request):
    order = Order.objects.create(client_email = request.POST['client_email'],
        client_name = request.POST['client_name'],
        client_phone = request.POST['client_phone'],
        client_company = request.POST['client_company'],
        order_text = request.POST['order_text'])

    response = redirect(reverse('catalog:order'))
    response.set_cookie('order_success', '', max_age=1000)

    notificate_manager(order)

    return response


def notificate_manager(order):
    dynamic_options = Option.get_dynamic_options()

    activate(settings.LANGUAGE_CODE)

    subject = '{} - {} - {} {}'.format(dynamic_options['brand_name'],
        _('New order'), order.client_name, order.client_company)
    message = '{}\n{}: {}\n{}: {}\n{}: {}\n{}: {}\n{}: \n{}\n'.format(
        _('New order'),
        Order.get_verbose_name('client_name'), order.client_name,
        Order.get_verbose_name('client_company'), order.client_company,
        Order.get_verbose_name('client_email'), order.client_email,
        Order.get_verbose_name('client_phone'), order.client_phone,
        Order.get_verbose_name('order_text'), order.order_text)

    send_mail(subject, message, settings.EMAIL_HOST_USER,
        [dynamic_options['email']], fail_silently=False)

    deactivate()


def render_with_dynamic_options(request, template, context=None):
    new_context = Option.get_dynamic_options()
    if context is not None:
        new_context.update(context)

    return render(request, template, new_context)

catalog/templates/catalog/about_us.html
{% extends 'catalog/base.html' %}
{% load i18n %}

{% block meta_info %}
    <meta name="description" content="{{ pages_meta_description }}">
    <meta name="keywords" content="{{ pages_meta_keywords }}">
    <title>{% trans 'About Us' %} | {{ pages_title }}</title>
{% endblock %}

{% block nav_link_status-about %}
    class="active"
{% endblock %}

{% block main %}
 <div class="container down">
    <div class="bg">
        <div class="row">
            <div class="col-sm-12">
                <div class="about-us-content">
                    <h2 class="title text-center">{% trans 'About Us' %}</h2>
                    {{ about_us_content }}
                </div>
            </div>
        </div>
    </div>
 </div>
{% endblock %}

catalog/templates/catalog/base.html
{% load i18n %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
	{% block meta_info %}
    {% endblock %}
	<link rel="shortcut icon" type="image/x-icon" href="/static/catalog/images/favicon.ico">
    <link href="/static/catalog/css/bootstrap.min.css" rel="stylesheet">
    <link href="/static/catalog/css/font-awesome.min.css" rel="stylesheet">
	<link href="/static/catalog/css/main.css" rel="stylesheet">
	<link href="/static/catalog/css/responsive.css" rel="stylesheet">
    <!--[if lt IE 9]>
    <script src="/static/catalog/js/html5shiv.js"></script>
    <script src="/static/catalog/js/respond.min.js"></script>
    <![endif]-->
    {% block styles %}
    {% endblock %}
    <link rel="shortcut icon" href="images/ico/favicon.ico">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="images/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="images/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="images/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="images/ico/apple-touch-icon-57-precomposed.png">
</head><!--/head-->

<body>
	<header id="header"><!--header-->
		<div class="header_top"><!--header_top-->
			<div class="container">
				<div class="row">
					<div class="col-sm-6">
						<div class="contactinfo">
							<ul class="nav nav-pills">
								<li><a href="#"><i class="fa fa-phone"></i> {{ phone_number }}</a></li>
								<li><a href="#"><i class="fa fa-envelope"></i> {{ email }}</a></li>
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div><!--/header_top-->

		<div class="header-middle"><!--header-middle-->
			<div class="container">
				<div class="row">
					<div class="col-sm-4">
						<div class="pull-left">
							<a href="{% url 'catalog:index_page' %}">
								<img src="/static/catalog/images/logo.png" alt="">
							</a>
						</div>
					</div>
                    <div class="col-sm-8">
						<div class="shop-menu pull-right">
							<ul class="nav navbar-nav">
								{% for url, lang in available_languages %}
									<li><a href="{{ url }}">{{ lang }}</a></li>
								{% endfor %}
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div><!--/header-middle-->

		<div class="header-bottom"><!--header-bottom-->
			<div class="container">
				<div class="row">
					<div class="col-sm-12">
						<div class="navbar-header">
							<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
								<span class="sr-only">Toggle navigation</span>
								<span class="icon-bar"></span>
								<span class="icon-bar"></span>
								<span class="icon-bar"></span>
							</button>
						</div>
						<div class="mainmenu pull-left">
							<ul class="nav navbar-nav collapse navbar-collapse">
								<li>
									<a {% block nav_link_status-index %}{% endblock %}
                                       href="{% url 'catalog:index_page' %}">{% trans 'Home' %}</a>
                                </li>
                                <li>
                                    <a {% block nav_link_status-filter %}{% endblock %}
                                       href="{% url 'catalog:filter_clothes' %}">{% trans 'Products' %}</a>
                                </li>
								<li>
                                    <a {% block nav_link_status-about %}{% endblock %}
                                       href="{% url 'catalog:about_us' %}">{% trans 'About Us' %}</a>
                                </li>
								<li>
                                    <a {% block nav_link_status-contact %}{% endblock %}
                                       href="{% url 'catalog:contact' %}">{% trans 'Contact' %}</a>
                                </li>
								<li>
                                    <a {% block nav_link_status-order %}{% endblock %}
                                       href="{% url 'catalog:order' %}">{% trans 'Order' %}</a>
                                </li>
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div><!--/header-bottom-->
	</header><!--/header-->

    {% block main %}
    {% endblock %}

	<footer id="footer"><!--Footer-->
		<div class="footer-bottom">
			<div class="container">
				<div class="row">
					<p class="pull-left">{{ footer_copyright }}</p>
				</div>
			</div>
		</div>
	</footer><!--/Footer-->

    <script src="/static/catalog/js/jquery.js"></script>
	<script src="/static/catalog/js/bootstrap.min.js"></script>
    <script src="/static/catalog/js/main.js"></script>
    {% block scripts %}
    {% endblock %}
</body>
</html>

catalog/templates/catalog/clothes_partial.html
{% load i18n %}

{% for clothing in clothes %}
    <div class="col-sm-4 col-xs-6">
        <div class="product-image-wrapper">
            <div class="single-products">
                <div class="productinfo text-center">
                    <img src="{{ clothing.photo.thumbnail.url }}" alt="" />
                    <p>
                        <a rel="prettyPhoto" href="{{ clothing.photo.url }}" title="{{ clothing.title }}">
                            {{ clothing.title }}
                        </a>
                    </p>
                </div>
                <div class="product-overlay">
                    <div class="overlay-content">
                        <p>
                            {% if clothing.description %}
                                {{ clothing.description }}<br><br>
                            {% endif %}
                            {% trans 'Gender/Age' %}: {{ clothing.get_gender_display }}<br>
                            {% trans 'Season' %}: {{ clothing.get_season_display }}<br>
                            {% trans 'Category' %}: {{ clothing.category }}<br>
                            <hr>
                            <a rel="prettyPhoto" href="{{ clothing.photo.url }}" title="{{ clothing.title }}">
                                {{ clothing.title }}
                            </a>

                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endfor %}

catalog/templates/catalog/contact.html
{% extends 'catalog/base.html' %}
{% load i18n %}

{% block meta_info %}
    <meta name="description" content="{{ pages_meta_description }}">
    <meta name="keywords" content="{{ pages_meta_keywords }}">
    <title>{% trans 'Contact' %} | {{ pages_title }}</title>
{% endblock %}

{% block nav_link_status-contact %}
    class="active"
{% endblock %}

{% block main %}
<div class="container down">
    <div class="bg">
        <div class="row">
            <div class="col-sm-12">
                <div class="about-us-content">
                    <h2 class="title text-center">{% trans 'Contact Us' %}</h2>
                    <address>
                        <p>{% trans 'Address' %}: {{ address }}</p>
                        <p>{% trans 'Phone' %}: {{ phone_number }}</p>
                        <p>{% trans 'Email' %}: {{ email }}</p>
                    </address>
                </div>
            </div>
        </div>
    </div>
 </div>
{% endblock %}

{% block scripts %}
    <script src="/static/catalog/js/contact.js"></script>
{% endblock %}

catalog/templates/catalog/filter.html
{% extends 'catalog/base.html' %}
{% load i18n %}
{% load catalog_extras %}

{% block meta_info %}
    <meta name="description" content="{{ pages_meta_description }}">
    <meta name="keywords" content="{{ pages_meta_keywords }}">
    <title>{% trans 'Products' %} | {{ pages_title }}</title>
{% endblock %}

{% block styles %}
	<link href="/static/catalog/css/prettyPhoto.css" rel="stylesheet">
{% endblock %}

{% block nav_link_status-filter %}
    class="active"
{% endblock %}

{% block main %}
	<section>
		<div class="container down">
			<div class="row">
                {% render_filters filters_list %}
				<div class="col-sm-9 padding-right">
					<div class="features_items"><!--features_items-->
						<h2 class="title text-center">{% trans 'Items' %}</h2>
                        {% render_clothes_grid clothes %}
						<div class="clearfix"></div>
                        {% render_pagination page_num pages_num %}
					</div>
				</div>
			</div>
		</div>
	</section>
{% endblock %}

{% block scripts %}
	<script src="/static/catalog/js/jquery.prettyPhoto.js"></script>
    <script type="text/javascript" charset="utf-8">
        $(document).ready(function(){
            $("a[rel^='prettyPhoto']").prettyPhoto({
                animationSpeed: 'normal',
                opacity: 0.80,
                showTitle: true,
                social_tools: ''
			});
        });
    </script>
{% endblock %}

catalog/templates/catalog/filters_partial.html
{% load i18n %}
{% load catalog_query_string %}

<div class="col-sm-3">
    <div class="left-sidebar">
        {% for filter in filters_list %}
            <h2>{{ filter.caption }}</h2>
            <div class="panel-group category-products" id="accordian">
                {% for choice in filter.choices %}
                    <div class="panel panel-default {% if choice.is_currently_chosen %}active{% endif %}">
                        <div class="panel-heading">
                            <h4 class="panel-title">
                                <a href="{% url 'catalog:filter_clothes' %}{% set_query_string_param filter.url_name choice.url_name 'page' None %}">
                                    {{ choice.caption}}
                                </a>
                            </h4>
                        </div>
                    </div>
                {% endfor %}
                <div class="panel panel-default clear-filter">
                    <div class="panel-heading">
                        <h4 class="panel-title">
                            <a href="{% url 'catalog:filter_clothes' %}{% set_query_string_param filter.url_name None 'page' None %}">
                                {% trans 'Clear' %}
                            </a>
                        </h4>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>

catalog/templates/catalog/index.html
{% extends 'catalog/base.html' %}
{% load i18n %}
{% load catalog_extras %}
{% block meta_info %}
    <meta name="description" content="{{ pages_meta_description }}">
    <meta name="keywords" content="{{ pages_meta_keywords }}">
    <title>{% trans 'Home' %} | {{ pages_title }}</title>
{% endblock %}

{% block styles %}
	<link href="/static/catalog/css/prettyPhoto.css" rel="stylesheet">
{% endblock %}

{% block nav_link_status-index %}
    class="active"
{% endblock %}

{% block main %}
	<section id="slider"><!--slider-->
		<div class="container">
			<div class="row">
				<div class="col-sm-12">
					<div id="slider-carousel" class="carousel slide" data-ride="carousel">
						<ol class="carousel-indicators">
							<li data-target="#slider-carousel" data-slide-to="0" class="active"></li>
							<li data-target="#slider-carousel" data-slide-to="1"></li>
							<li data-target="#slider-carousel" data-slide-to="2"></li>
						</ol>

						<div class="carousel-inner">
							<div class="item active">
								<div class="col-sm-6">
									<h1><span>{{ brand_name }}</span></h1>
									<h2>{{ carousel_subheader_1 }}</h2>
									<p>{{ carousel_text_1 }}</p>
								</div>
								<div class="col-sm-6">
									<img src="/static/catalog/images/home/main11.png" class="girl img-responsive" alt="" />
								</div>
							</div>
							<div class="item">
								<div class="col-sm-6">
									<h1><span>{{ brand_name }}</span></h1>
									<h2>{{ carousel_subheader_2 }}</h2>
									<p>{{ carousel_text_2 }}</p>
								</div>
								<div class="col-sm-6">
									<img src="/static/catalog/images/home/main22.png" class="girl img-responsive" alt="" />
								</div>
							</div>

							<div class="item">
								<div class="col-sm-6">
									<h1><span>{{ brand_name }}</span></h1>
									<h2>{{ carousel_subheader_3 }}</h2>
									<p>{{ carousel_text_3 }}</p>
								</div>
								<div class="col-sm-6">
									<img src="/static/catalog/images/home/main33.png" class="girl img-responsive" alt="" />
								</div>
							</div>

						</div>

						<a href="#slider-carousel" class="left control-carousel hidden-xs" data-slide="prev">
							<i class="fa fa-angle-left"></i>
						</a>
						<a href="#slider-carousel" class="right control-carousel hidden-xs" data-slide="next">
							<i class="fa fa-angle-right"></i>
						</a>
					</div>

				</div>
			</div>
		</div>
	</section><!--/slider-->

	<section>
		<div class="container">
			<div class="row">
                {% render_filters filters_list %}
				<div class="col-sm-9 padding-right">
					<div class="features_items"><!--features_items-->
						<h2 class="title text-center">{% trans 'Features Items' %}</h2>
                        {% render_clothes_grid clothes %}
					</div>
				</div>
			</div>
		</div>
	</section>
{% endblock %}

{% block scripts %}
	<script src="/static/catalog/js/jquery.prettyPhoto.js"></script>
    <script type="text/javascript" charset="utf-8">
        $(document).ready(function(){
            $("a[rel^='prettyPhoto']").prettyPhoto({
                animationSpeed: 'normal',
                opacity: 0.80,
                showTitle: true,
                social_tools: ''
			});
        });
    </script>
{% endblock %}

catalog/templates/catalog/order.html
{% extends 'catalog/base.html' %}
{% load i18n %}
{% load catalog_extras %}

{% block meta_info %}
    <meta name="description" content="{{ pages_meta_description }}">
    <meta name="keywords" content="{{ pages_meta_keywords }}">
    <title>{% trans 'Order' %} | {{ pages_title }}</title>
{% endblock %}

{% block nav_link_status-order %}
    class="active"
{% endblock %}

{% block main %}
<div class="container down">
    <div class="bg">
        <div class="row">
            <div class="col-sm-8 col-sm-offset-2">
                <div class="about-us-content">
                    <h2 class="title text-center">{% trans 'Order' %}</h2>
                    <form
                        class="form-horizontal
                            {% if order_status == 'success' %}
                                form-success
                            {% elif order_status == 'fail' %}
                                form-danger
                            {% endif %}
                        "
                        method="post"
                    >
                        {% if order_status %}
                            <div class="row">
                                <div class="col-lg-8 col-lg-offset-2">
                                    {% if order_status == 'success' %}
                                        <div class="alert alert-success">
                                            {% blocktrans %}Your order is accepted. We will contact you in short time.{% endblocktrans %}
                                        </div>
                                    {% elif order_status == 'fail' %}
                                        <div class="alert alert-danger">
                                            {% blocktrans %}Please fix errors below.{% endblocktrans %}
                                        </div>
                                    {% endif %}
                                </div>
                            </div>
                        {% endif %}
                        {% csrf_token %}
                        <fieldset>
                            {% for field in form %}
                                <div class="form-group {% if field.errors %}has-error{% endif %}">
                                    {{ field.label_tag|set_class:'col-lg-2 control-label' }}
                                    <div class="col-lg-8">
                                        {{ field|set_class:'form-control' }}
                                        {% for error in field.errors %}
                                            <span class="help-block">{{ error }}</span>
                                        {% endfor %}
                                    </div>
                                </div>
                            {% endfor %}
                            <div class="form-group">
                                <div class="col-lg-8 col-lg-offset-2">
                                    <button type="submit" class="btn btn-primary">{% trans 'Submit' %}</button>
                                </div>
                            </div>
                        </fieldset>
                    </form>
                </div>
            </div>
        </div>
    </div>
 </div>
{% endblock %}

catalog/templates/catalog/pagination_partial.html
{% load catalog_query_string %}
{% if buttons %}
<ul class="pagination">
    {% for button_type, page_num in buttons %}
        {% if button_type == 'first' %}
            <li>
                <a href="{% set_query_string_param 'page' page_num %}">
                    <i class="fa fa-angle-double-left"></i>
                </a>
            </li>
        {% elif button_type = 'prev' %}
            <li>
                <a href="{% set_query_string_param 'page' page_num %}">
                    <i class="fa fa-angle-left"></i>
                </a>
            </li>
        {% elif button_type == 'page' %}
            <li>
                <a href="{% set_query_string_param 'page' page_num %}">
                    {{ page_num }}
                </a>
            </li>
        {% elif button_type == 'cur_page' %}
            <li class="active">
                <a href="{% set_query_string_param 'page' page_num %}">
                    {{ page_num }}
                </a>
            </li>
        {% elif button_type == 'next' %}
            <li>
                <a href="{% set_query_string_param 'page' page_num %}">
                    <i class="fa fa-angle-right"></i>
                </a>
            </li>
        {% else %}
            <li>
                <a href="{% set_query_string_param 'page' page_num %}">
                    <i class="fa fa-angle-double-right"></i>
                </a>
            </li>
        {% endif %}
    {% endfor %}
</ul>
{% endif %}